# Generated by Django 3.0.5 on 2021-03-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='titles', to='title.Genre'),
        ),
    ]
