# Generated by Django 3.0.5 on 2021-03-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0002_auto_20210324_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['slug']},
        ),
    ]
