# Generated by Django 3.0.5 on 2021-03-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0003_auto_20210324_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['slug']},
        ),
    ]
