# Generated by Django 3.0.5 on 2021-03-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('title', '0006_auto_20210328_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={'ordering': ('pk',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
