# Generated by Django 3.0.5 on 2021-03-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20210328_1927'),
        ('review', '0008_auto_20210328_1800'),
    ]

    operations = [
    ]
