# Generated by Django 3.0.5 on 2021-03-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_merge_20210328_2106'),
        ('review', '0009_auto_20210330_2033'),
    ]

    operations = [
    ]
