# Generated by Django 3.0.5 on 2021-03-28 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20210328_1927'),
        ('comment', '0006_auto_20210328_1800'),
    ]

    operations = [
    ]
