# Generated by Django 3.0.5 on 2021-03-30 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20210330_2033'),
        ('comment', '0007_merge_20210328_2107'),
    ]

    operations = [
    ]
